### ISSUE TITLE
paper to cite?

### ISSUE THREAD

**Issue by pog87** [piloubazin/cbstools-public#10]
Hello. 
 I would like to find a reference paper in order to correctly cite this work.

Best,
Davide

**Comment by piloubazin** [comment]
So far the closest published article is:
https://www.ncbi.nlm.nih.gov/pubmed/23623972

We submitted a paper in November, so hopefully it will be out soon. You can cite it as 'under review' like this:
JM Huntenburg, CJ Steele, P-L Bazin, "Nighres: Processing tools for high-resolution neuroimaging", under review.
