### ISSUE TITLE
Programmatic installation of CBS Tools

### ISSUE THREAD

**Issue by chrisgorgo** [piloubazin/cbstools-public#11]
A while ago I was trying to programmatically install CBS Tools (as part of a Dockerfile), but got stuck on MIPAV dependency which required manual download. Are there any updates on this? Is it possible to incorporate CBS Tools into Docker images?

**Comment by piloubazin** [comment]
Yes!! Now you can use **nighres** which wraps around and extends CBSTools. Thanks to Julia Huntenburg's efforts, it's all ready for installation ('pip install nighres' should work...), much better documented, and includes examples (using 7T TRT data) and even a Docker image :)

**Comment by chrisgorgo** [comment]
Awesome thanks!
