### ISSUE TITLE
Problem with brain-segmentation-MP2RAGE-7T-native.LayoutXML

### ISSUE THREAD

**Issue by ingo-m** [piloubazin/cbstools-public#7]
I think there is a small bug in an example layout. I am using version 3.0.9 of CBS tools, and the problematic layout is the following one:
~/mipav/plugins/layouts-r3.0/brain-segmentation-MP2RAGE-7T-native.LayoutXML
The T1 image is reoriented twice, once after volume thresholding, and another time in the reorientation module for the UNI image. This is a small thing, but I think it caused bad segmentation results, for people unfamiliar with the JIST tool it may take some time to figure it out.
![brain_segmentation_mp2rage_7t_native](https://user-images.githubusercontent.com/10960892/28265608-f364f04a-6af0-11e7-9456-a5a9cce97bac.png)

**Comment by piloubazin** [comment]
Yes, this was incorrect. A few of the "standard" analysis pipelines are now old and I need to rebuild them for the new github version. Thanks for the heads-up!
